-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS public.carta
(
    n_carta integer PRIMARY KEY,
    nombre character varying(50),
    categoria character varying(30),
	precio double precision
);

INSERT INTO carta VALUES(1, 'Roman Reigns', 'Wrestlemania 40', 5.99);
SELECT * FROM catalogo_cartas

/*------------------------------------------------------------------------------------*/

CREATE TABLE IF NOT EXISTS public.catalogo_cartas
(
	n_carta integer PRIMARY KEY,
	nombre character varying(50),
    precio double precision,
	stock integer,
	CONSTRAINT fk_n_carta FOREIGN KEY(n_carta) REFERENCES carta(n_carta)
);

CREATE OR REPLACE FUNCTION registrar_catalogo()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO catalogo_cartas VALUES(NEW.n_carta, NEW.nombre, NEW.precio, 100);
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER registrar_nuevo_producto_catalogo
AFTER INSERT ON carta
FOR EACH ROW
EXECUTE FUNCTION registrar_catalogo();

CREATE OR REPLACE FUNCTION eliminar_catalogo()
RETURNS TRIGGER AS $$
BEGIN
DELETE FROM catalogo_cartas WHERE n_carta = NEW.n_carta;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER eliminar_producto_catalogo
BEFORE DELETE ON carta
FOR EACH ROW
EXECUTE FUNCTION eliminar_catalogo();

/*------------------------------------------------------------------------------------*/
CREATE TABLE IF NOT EXISTS public.luchador(
	n_carta integer PRIMARY KEY,
	fuerza int,
	resistencia int,
	velocidad int,
	carisma int,
	CONSTRAINT fk_n_carta_carta FOREIGN KEY (n_carta) REFERENCES carta(n_carta)
);

INSERT INTO luchador VALUES(1, 21, 19, 18, 20)

/*------------------------------------------------------------------------------------*/

CREATE TABLE IF NOT EXISTS public.categoria
DELETE FROM catalogocarta where n_carta=1